name: slideable_pop_scope
description: "A new Flutter package project."
version: 1.0.0
homepage:
repository: https://github.com/HAM02020/slideable_pop_scope

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: